name: Deploy site (branch)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: false  # keep cache OFF for now

      - name: Install & build
        shell: bash -l {0}
        env:
          JEKYLL_ENV: production
        run: |
          bundle -v || gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build --trace
          touch _site/.nojekyll     # critical: stop GH from rebuilding

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages

